name: "GHG Add Metadata"

on:
  push:
    branches:    
      - '*'
jobs:
  metadata:
    name: "GHG Add Metadata"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Extract branch name
      shell: bash
      run: echo 'BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')' >> $GITHUB_ENV

    - name: Add metadata upon commit
      run: |
        npm install fs util promisify
        node scripts/ghg.js
