name: List PRs to rebase upon new PR has been merged into train
on:
  pull_request:
    branches:
      - train
    types: [closed]

jobs:
  list-and-rebase-to-train:
    name: "Rebase all PRs to train"
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'rt-2.0')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Check comments
        env:
          CREATE_BRANCH_TOKEN: ${{ secrets.CREATE_BRANCH_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          PUSH_GITHUB_USER: ${{ secrets.PUSH_GITHUB_USER }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          npm install compare-versions node-fetch fs inquirer
          node --trace-warnings scripts/rebaseAllTrainPRs.js train
