name: List PRs to rebase upon new PR has been merged into train
on:
  pull_request:
    branches:
      - train
    types: [closed]

jobs:
  merged-to-develop:
    name: Merge ${{  github.head_ref }} to develop"
    if: github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'temporary')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
      - name: Check comments
        env:
          CREATE_BRANCH_TOKEN: ${{ secrets.CREATE_BRANCH_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          PUSH_GITHUB_USER: ${{ secrets.PUSH_GITHUB_USER }}
        run: |
          npm install compare-versions node-fetch fs
          node --trace-warnings scripts/listPRsAndRebase.js train
