name: "Spin-Web Workflow"

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  releaser:
    name: "Spin-Web Release Start Workflow"
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'integration-') && contains(github.event.pull_request.labels.*.name, 'rt-2.0-spin-web')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - name: Commit on master triggers merge onto integration branch
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
        PUSH_GITHUB_USER: ${{ secrets.PUSH_GITHUB_USER }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        npm install compare-versions node-fetch fs inquirer
        node scripts/releaseSpinWeb.js release-start
